return {
  -- 'supermaven-inc/supermaven-nvim',
  -- build = ':SupermavenUseFree',
  -- cmd = 'SupermavenStart',
  -- -- event = 'InsertEnter',
  -- lazy = false,
  -- opts = {
  --   disable_keymaps = true,
  --   disable_inline_completion = true,
  --
  --   ignore_filetypes = {
  --     help = true,
  --     gitrebase = true,
  --     hgcommit = true,
  --     svn = true,
  --     cvs = true,
  --     ['.'] = true,
  --   },
  --
  --   log_level = 'info',
  --
  --   condition = function()
  --     return false -- always enabled unless condition returns true
  --   end,
  -- },
}
