return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  dependencies = { 'echasnovski/mini.icons', 'nvim-tree/nvim-web-devicons' },
  opts = {
    preset = 'helix',
    delay = 0,
    spec = {
      { '<leader>f', group = 'Format' },
      { '<leader>s', group = 'Search' },
      { '<leader>t', group = 'Test' },
      { '<leader>g', group = 'Git' },
      { '<leader>h', group = 'Git Hunk', mode = { 'n', 'v' } },
      { '<leader>r', group = 'Refactor', mode = { 'n', 'v' } },
      { 'gp', group = 'Preview' },
      { 'gr', group = 'LSP' },
      { '<leader>t', group = 'Toggle' },
      { '<leader>b', group = 'deBug' },
      { '<leader>y', hidden = true },
      { '<leader>Y', hidden = true },
      { '<leader>p', hidden = true },
      { '<leader>d', hidden = true },
    },
  },
}
