return {
  -- 'nosduco/remote-sshfs.nvim',
  -- dependencies = {
  --   {
  --     'nvim-telescope/telescope.nvim',
  --     lazy = true,
  --     dependencies = { 'nvim-lua/plenary.nvim' },
  --   },
  -- },
  -- opts = {},
  -- keys = {
  --   {
  --     '<leader>R',
  --     function()
  --       vim.ui.input({
  --         prompt = 'RemoteSSHFSConnect: ',
  --       }, function(input)
  --         if input and input ~= '' then
  --           vim.cmd('RemoteSSHFSConnect ' .. input)
  --         end
  --       end)
  --     end,
  --     desc = 'Remote SSH Connect',
  --   },
  -- },
}

-- return {
-- 	"amitds1997/remote-nvim.nvim",
-- 	version = "*",         -- Pin to GitHub releases
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim", -- For standard functions
-- 		"MunifTanjim/nui.nvim", -- To build the plugin UI
-- 		-- "nvim-telescope/telescope.nvim", -- For picking b/w different remote methods
-- 	},
-- 	config = true,
-- }
